In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

In [2]:
df = pd.read_csv("telecom_clientes.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   Churn             7043 non-null   str
 2   Gender            7043 non-null   str
 3   SeniorCitizen     7043 non-null   int64
 4   Partner           7043 non-null   str
 5   Dependents        7043 non-null   str
 6   Tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   str
 8   MultipleLines     7043 non-null   str
 9   InternetService   7043 non-null   str
 10  OnlineSecurity    7043 non-null   str
 11  OnlineBackup      7043 non-null   str
 12  DeviceProtection  7043 non-null   str
 13  TechSupport       7043 non-null   str
 14  StreamingTV       7043 non-null   str
 15  StreamingMovies   7043 non-null   str
 16  Contract          7043 non-null   str
 17  PaperlessBilling  7043 non-null   str
 18  PaymentMethod     7043 non-null   str
 19  ChargesMonthly    7043 non-null   float64
 20  ChargesTotal      7032 non-null   float64
 21  CuentasDiarias    7043 non-null   float64
dtypes: float64(3), int64(2), str(17)
memory usage: 1.9 MB

In [4]:
proporcion_evasion = df['Churn'].value_counts(normalize=True).to_frame()

In [5]:
proporcion_evasion

       proportion
Churn
no        0.73463
yes       0.26537

In [6]:
round(proporcion_evasion.loc['yes'],2)

proportion    0.27
Name: yes, dtype: float64

In [7]:
tasa_pago = pd.crosstab(df["Gender"], df["Churn"], normalize=True)
    
tasa_pago.sort_values(by='yes', ascending=True, inplace=True)

In [8]:
tasa_pago.info()

<class 'pandas.DataFrame'>
Index: 2 entries, male to female
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   no      2 non-null      float64
 1   yes     2 non-null      float64
dtypes: float64(2)
memory usage: 59.0 bytes

In [9]:
tasa_pago.index

Index(['male', 'female'], dtype='str', name='Gender')

In [10]:
tasa_pago['yes']

Gender
male      0.132046
female    0.133324
Name: yes, dtype: float64

In [11]:
tasa_pago = pd.crosstab(df['Gender'], df["Churn"], normalize='index')
    
tasa_pago.sort_values(by='yes', ascending=True, inplace=True)

In [12]:
tasa_pago.info()

<class 'pandas.DataFrame'>
Index: 2 entries, male to female
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   no      2 non-null      float64
 1   yes     2 non-null      float64
dtypes: float64(2)
memory usage: 59.0 bytes

In [13]:
tasa_pago

Churn         no       yes
Gender
male    0.738397  0.261603
female  0.730791  0.269209

In [14]:
tasa_pago.index

Index(['male', 'female'], dtype='str', name='Gender')

In [15]:
for categoria in tasa_pago.index:
    tasa_categoria = tasa_pago.loc[categoria, 'yes']

    print(tasa_categoria)

0.2616033755274262
0.26920871559633025

In [58]:
servicios = df[['PhoneService', 'MultipleLines',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies']]

servicios_columnas = ['PhoneService', 
                      'MultipleLines', 
                      'OnlineSecurity', 
                      'OnlineBackup', 
                      'DeviceProtection',
                       'TechSupport', 
                       'StreamingTV', 
                       'StreamingMovies']

servicios[servicios_columnas] = np.where(servicios[servicios_columnas] == 'yes', 1, 0)

servicios['InternetService'] = np.where((df['InternetService'] == 'dsl') | (df['InternetService'] == 'fiber optic'), 1, 0)

servicios['Churn'] = np.where(df['Churn'] == 'yes', 1, 0)

servicios_columnas.append('InternetService')

servicios['numero_servicios'] = servicios[servicios_columnas].sum(axis=1)

In [59]:
servicios

,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,InternetService,Churn,numero_servicios
0,1,0,0,1,0,1,1,0,1,0,5
1,1,1,0,0,0,0,0,1,1,0,4
2,1,0,0,0,1,0,0,0,1,1,3
3,1,0,0,1,1,0,1,1,1,1,6
4,1,0,0,0,0,1,1,0,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,0,0,1,0,0,1,0,4
7039,1,1,0,0,0,0,0,1,1,1,4
7040,1,0,0,1,0,0,0,0,1,0,3
7041,1,0,1,0,1,1,0,1,1,0,6
7042,0,0,1,1,1,0,1,1,1,0,6

In [62]:
churn_servicios = pd.crosstab(servicios['numero_servicios'], servicios['Churn'], normalize='index')

churn_servicios.rename({0:'No', 1:'Yes'}, axis=1, inplace=True)

In [65]:
churn_servicios

Churn                   No       Yes
numero_servicios
1                 0.890823  0.109177
2                 0.690338  0.309662
3                 0.550827  0.449173
4                 0.635233  0.364767
5                 0.686551  0.313449
6                 0.744493  0.255507
7                 0.775148  0.224852
8                 0.875949  0.124051
9                 0.947115  0.052885